version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2023.12
    steps:
      - checkout
      - run: |
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$PATH:`pwd`/flutter/bin"
          echo 'export PATH="$PATH:`pwd`/flutter/bin"' >> $BASH_ENV
          flutter precache
          flutter doctor
          flutter upgrade
          flutter doctor
      - run: flutter pub get
      - run: flutter build apk
      - store_artifacts:
          path: build/app/outputs
